{{- if .Values.env -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-secrets
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.env }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
