{{- if .Values.cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-crt
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
stringData:
  pgbouncer.crt: |-
    {{- .Values.cert.crt | nindent 4}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-key
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
stringData:
  pgbouncer.key: |-
    {{- .Values.cert.key | nindent 4 }}
{{- end -}}
